repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            exclude: ^(proto|src/proto|tests/proto|lib)/
          - id: check-yaml
          - id: check-added-large-files
          - id: double-quote-string-fixer

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v2.4.1'
      hooks:
          - id: prettier
            exclude: ^(proto|src/proto|tests/proto|lib)/

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v8.5.0'
      hooks:
          - id: eslint
            exclude: ^(proto|src/proto|tests/proto|lib)/
