// source: evmos/claim/v1/claim.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
goog.exportSymbol('proto.evmos.claim.v1.Action', null, global);
goog.exportSymbol('proto.evmos.claim.v1.Claim', null, global);
goog.exportSymbol('proto.evmos.claim.v1.ClaimRecord', null, global);
goog.exportSymbol('proto.evmos.claim.v1.ClaimRecordAddress', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evmos.claim.v1.Claim = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.evmos.claim.v1.Claim, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evmos.claim.v1.Claim.displayName = 'proto.evmos.claim.v1.Claim';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evmos.claim.v1.ClaimRecordAddress = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.evmos.claim.v1.ClaimRecordAddress.repeatedFields_, null);
};
goog.inherits(proto.evmos.claim.v1.ClaimRecordAddress, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evmos.claim.v1.ClaimRecordAddress.displayName = 'proto.evmos.claim.v1.ClaimRecordAddress';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evmos.claim.v1.ClaimRecord = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.evmos.claim.v1.ClaimRecord.repeatedFields_, null);
};
goog.inherits(proto.evmos.claim.v1.ClaimRecord, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evmos.claim.v1.ClaimRecord.displayName = 'proto.evmos.claim.v1.ClaimRecord';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evmos.claim.v1.Claim.prototype.toObject = function(opt_includeInstance) {
  return proto.evmos.claim.v1.Claim.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evmos.claim.v1.Claim} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.claim.v1.Claim.toObject = function(includeInstance, msg) {
  var f, obj = {
    action: jspb.Message.getFieldWithDefault(msg, 1, 0),
    completed: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    claimableAmount: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evmos.claim.v1.Claim}
 */
proto.evmos.claim.v1.Claim.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evmos.claim.v1.Claim;
  return proto.evmos.claim.v1.Claim.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evmos.claim.v1.Claim} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evmos.claim.v1.Claim}
 */
proto.evmos.claim.v1.Claim.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.evmos.claim.v1.Action} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCompleted(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setClaimableAmount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evmos.claim.v1.Claim.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evmos.claim.v1.Claim.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evmos.claim.v1.Claim} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.claim.v1.Claim.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAction();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCompleted();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getClaimableAmount();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional Action action = 1;
 * @return {!proto.evmos.claim.v1.Action}
 */
proto.evmos.claim.v1.Claim.prototype.getAction = function() {
  return /** @type {!proto.evmos.claim.v1.Action} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.evmos.claim.v1.Action} value
 * @return {!proto.evmos.claim.v1.Claim} returns this
 */
proto.evmos.claim.v1.Claim.prototype.setAction = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional bool completed = 2;
 * @return {boolean}
 */
proto.evmos.claim.v1.Claim.prototype.getCompleted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.evmos.claim.v1.Claim} returns this
 */
proto.evmos.claim.v1.Claim.prototype.setCompleted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string claimable_amount = 3;
 * @return {string}
 */
proto.evmos.claim.v1.Claim.prototype.getClaimableAmount = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.evmos.claim.v1.Claim} returns this
 */
proto.evmos.claim.v1.Claim.prototype.setClaimableAmount = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.evmos.claim.v1.ClaimRecordAddress.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evmos.claim.v1.ClaimRecordAddress.prototype.toObject = function(opt_includeInstance) {
  return proto.evmos.claim.v1.ClaimRecordAddress.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evmos.claim.v1.ClaimRecordAddress} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.claim.v1.ClaimRecordAddress.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: jspb.Message.getFieldWithDefault(msg, 1, ""),
    initialClaimableAmount: jspb.Message.getFieldWithDefault(msg, 2, ""),
    actionsCompletedList: (f = jspb.Message.getRepeatedBooleanField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evmos.claim.v1.ClaimRecordAddress}
 */
proto.evmos.claim.v1.ClaimRecordAddress.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evmos.claim.v1.ClaimRecordAddress;
  return proto.evmos.claim.v1.ClaimRecordAddress.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evmos.claim.v1.ClaimRecordAddress} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evmos.claim.v1.ClaimRecordAddress}
 */
proto.evmos.claim.v1.ClaimRecordAddress.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setInitialClaimableAmount(value);
      break;
    case 3:
      var values = /** @type {!Array<boolean>} */ (reader.isDelimited() ? reader.readPackedBool() : [reader.readBool()]);
      for (var i = 0; i < values.length; i++) {
        msg.addActionsCompleted(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evmos.claim.v1.ClaimRecordAddress.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evmos.claim.v1.ClaimRecordAddress.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evmos.claim.v1.ClaimRecordAddress} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.claim.v1.ClaimRecordAddress.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInitialClaimableAmount();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getActionsCompletedList();
  if (f.length > 0) {
    writer.writePackedBool(
      3,
      f
    );
  }
};


/**
 * optional string address = 1;
 * @return {string}
 */
proto.evmos.claim.v1.ClaimRecordAddress.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.evmos.claim.v1.ClaimRecordAddress} returns this
 */
proto.evmos.claim.v1.ClaimRecordAddress.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string initial_claimable_amount = 2;
 * @return {string}
 */
proto.evmos.claim.v1.ClaimRecordAddress.prototype.getInitialClaimableAmount = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.evmos.claim.v1.ClaimRecordAddress} returns this
 */
proto.evmos.claim.v1.ClaimRecordAddress.prototype.setInitialClaimableAmount = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated bool actions_completed = 3;
 * @return {!Array<boolean>}
 */
proto.evmos.claim.v1.ClaimRecordAddress.prototype.getActionsCompletedList = function() {
  return /** @type {!Array<boolean>} */ (jspb.Message.getRepeatedBooleanField(this, 3));
};


/**
 * @param {!Array<boolean>} value
 * @return {!proto.evmos.claim.v1.ClaimRecordAddress} returns this
 */
proto.evmos.claim.v1.ClaimRecordAddress.prototype.setActionsCompletedList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {boolean} value
 * @param {number=} opt_index
 * @return {!proto.evmos.claim.v1.ClaimRecordAddress} returns this
 */
proto.evmos.claim.v1.ClaimRecordAddress.prototype.addActionsCompleted = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.evmos.claim.v1.ClaimRecordAddress} returns this
 */
proto.evmos.claim.v1.ClaimRecordAddress.prototype.clearActionsCompletedList = function() {
  return this.setActionsCompletedList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.evmos.claim.v1.ClaimRecord.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evmos.claim.v1.ClaimRecord.prototype.toObject = function(opt_includeInstance) {
  return proto.evmos.claim.v1.ClaimRecord.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evmos.claim.v1.ClaimRecord} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.claim.v1.ClaimRecord.toObject = function(includeInstance, msg) {
  var f, obj = {
    initialClaimableAmount: jspb.Message.getFieldWithDefault(msg, 1, ""),
    actionsCompletedList: (f = jspb.Message.getRepeatedBooleanField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evmos.claim.v1.ClaimRecord}
 */
proto.evmos.claim.v1.ClaimRecord.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evmos.claim.v1.ClaimRecord;
  return proto.evmos.claim.v1.ClaimRecord.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evmos.claim.v1.ClaimRecord} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evmos.claim.v1.ClaimRecord}
 */
proto.evmos.claim.v1.ClaimRecord.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInitialClaimableAmount(value);
      break;
    case 2:
      var values = /** @type {!Array<boolean>} */ (reader.isDelimited() ? reader.readPackedBool() : [reader.readBool()]);
      for (var i = 0; i < values.length; i++) {
        msg.addActionsCompleted(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evmos.claim.v1.ClaimRecord.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evmos.claim.v1.ClaimRecord.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evmos.claim.v1.ClaimRecord} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.claim.v1.ClaimRecord.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInitialClaimableAmount();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getActionsCompletedList();
  if (f.length > 0) {
    writer.writePackedBool(
      2,
      f
    );
  }
};


/**
 * optional string initial_claimable_amount = 1;
 * @return {string}
 */
proto.evmos.claim.v1.ClaimRecord.prototype.getInitialClaimableAmount = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.evmos.claim.v1.ClaimRecord} returns this
 */
proto.evmos.claim.v1.ClaimRecord.prototype.setInitialClaimableAmount = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated bool actions_completed = 2;
 * @return {!Array<boolean>}
 */
proto.evmos.claim.v1.ClaimRecord.prototype.getActionsCompletedList = function() {
  return /** @type {!Array<boolean>} */ (jspb.Message.getRepeatedBooleanField(this, 2));
};


/**
 * @param {!Array<boolean>} value
 * @return {!proto.evmos.claim.v1.ClaimRecord} returns this
 */
proto.evmos.claim.v1.ClaimRecord.prototype.setActionsCompletedList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {boolean} value
 * @param {number=} opt_index
 * @return {!proto.evmos.claim.v1.ClaimRecord} returns this
 */
proto.evmos.claim.v1.ClaimRecord.prototype.addActionsCompleted = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.evmos.claim.v1.ClaimRecord} returns this
 */
proto.evmos.claim.v1.ClaimRecord.prototype.clearActionsCompletedList = function() {
  return this.setActionsCompletedList([]);
};


/**
 * @enum {number}
 */
proto.evmos.claim.v1.Action = {
  ACTION_UNSPECIFIED: 0,
  ACTION_VOTE: 1,
  ACTION_DELEGATE: 2,
  ACTION_EVM: 3,
  ACTION_IBC_TRANSFER: 4
};

goog.object.extend(exports, proto.evmos.claim.v1);
