// source: evmos/claim/v1/genesis.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var evmos_claim_v1_claim_pb = require('../../../evmos/claim/v1/claim_pb.js');
goog.object.extend(proto, evmos_claim_v1_claim_pb);
goog.exportSymbol('proto.evmos.claim.v1.GenesisState', null, global);
goog.exportSymbol('proto.evmos.claim.v1.Params', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evmos.claim.v1.GenesisState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.evmos.claim.v1.GenesisState.repeatedFields_, null);
};
goog.inherits(proto.evmos.claim.v1.GenesisState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evmos.claim.v1.GenesisState.displayName = 'proto.evmos.claim.v1.GenesisState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evmos.claim.v1.Params = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.evmos.claim.v1.Params, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evmos.claim.v1.Params.displayName = 'proto.evmos.claim.v1.Params';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.evmos.claim.v1.GenesisState.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evmos.claim.v1.GenesisState.prototype.toObject = function(opt_includeInstance) {
  return proto.evmos.claim.v1.GenesisState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evmos.claim.v1.GenesisState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.claim.v1.GenesisState.toObject = function(includeInstance, msg) {
  var f, obj = {
    params: (f = msg.getParams()) && proto.evmos.claim.v1.Params.toObject(includeInstance, f),
    claimRecordsList: jspb.Message.toObjectList(msg.getClaimRecordsList(),
    evmos_claim_v1_claim_pb.ClaimRecordAddress.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evmos.claim.v1.GenesisState}
 */
proto.evmos.claim.v1.GenesisState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evmos.claim.v1.GenesisState;
  return proto.evmos.claim.v1.GenesisState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evmos.claim.v1.GenesisState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evmos.claim.v1.GenesisState}
 */
proto.evmos.claim.v1.GenesisState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.evmos.claim.v1.Params;
      reader.readMessage(value,proto.evmos.claim.v1.Params.deserializeBinaryFromReader);
      msg.setParams(value);
      break;
    case 2:
      var value = new evmos_claim_v1_claim_pb.ClaimRecordAddress;
      reader.readMessage(value,evmos_claim_v1_claim_pb.ClaimRecordAddress.deserializeBinaryFromReader);
      msg.addClaimRecords(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evmos.claim.v1.GenesisState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evmos.claim.v1.GenesisState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evmos.claim.v1.GenesisState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.claim.v1.GenesisState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParams();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.evmos.claim.v1.Params.serializeBinaryToWriter
    );
  }
  f = message.getClaimRecordsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      evmos_claim_v1_claim_pb.ClaimRecordAddress.serializeBinaryToWriter
    );
  }
};


/**
 * optional Params params = 1;
 * @return {?proto.evmos.claim.v1.Params}
 */
proto.evmos.claim.v1.GenesisState.prototype.getParams = function() {
  return /** @type{?proto.evmos.claim.v1.Params} */ (
    jspb.Message.getWrapperField(this, proto.evmos.claim.v1.Params, 1));
};


/**
 * @param {?proto.evmos.claim.v1.Params|undefined} value
 * @return {!proto.evmos.claim.v1.GenesisState} returns this
*/
proto.evmos.claim.v1.GenesisState.prototype.setParams = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.evmos.claim.v1.GenesisState} returns this
 */
proto.evmos.claim.v1.GenesisState.prototype.clearParams = function() {
  return this.setParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.evmos.claim.v1.GenesisState.prototype.hasParams = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated ClaimRecordAddress claim_records = 2;
 * @return {!Array<!proto.evmos.claim.v1.ClaimRecordAddress>}
 */
proto.evmos.claim.v1.GenesisState.prototype.getClaimRecordsList = function() {
  return /** @type{!Array<!proto.evmos.claim.v1.ClaimRecordAddress>} */ (
    jspb.Message.getRepeatedWrapperField(this, evmos_claim_v1_claim_pb.ClaimRecordAddress, 2));
};


/**
 * @param {!Array<!proto.evmos.claim.v1.ClaimRecordAddress>} value
 * @return {!proto.evmos.claim.v1.GenesisState} returns this
*/
proto.evmos.claim.v1.GenesisState.prototype.setClaimRecordsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.evmos.claim.v1.ClaimRecordAddress=} opt_value
 * @param {number=} opt_index
 * @return {!proto.evmos.claim.v1.ClaimRecordAddress}
 */
proto.evmos.claim.v1.GenesisState.prototype.addClaimRecords = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.evmos.claim.v1.ClaimRecordAddress, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.evmos.claim.v1.GenesisState} returns this
 */
proto.evmos.claim.v1.GenesisState.prototype.clearClaimRecordsList = function() {
  return this.setClaimRecordsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evmos.claim.v1.Params.prototype.toObject = function(opt_includeInstance) {
  return proto.evmos.claim.v1.Params.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evmos.claim.v1.Params} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.claim.v1.Params.toObject = function(includeInstance, msg) {
  var f, obj = {
    enableClaim: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    airdropStartTime: (f = msg.getAirdropStartTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    durationUntilDecay: (f = msg.getDurationUntilDecay()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    durationOfDecay: (f = msg.getDurationOfDecay()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    claimDenom: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evmos.claim.v1.Params}
 */
proto.evmos.claim.v1.Params.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evmos.claim.v1.Params;
  return proto.evmos.claim.v1.Params.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evmos.claim.v1.Params} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evmos.claim.v1.Params}
 */
proto.evmos.claim.v1.Params.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableClaim(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setAirdropStartTime(value);
      break;
    case 3:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setDurationUntilDecay(value);
      break;
    case 4:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setDurationOfDecay(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setClaimDenom(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evmos.claim.v1.Params.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evmos.claim.v1.Params.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evmos.claim.v1.Params} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.claim.v1.Params.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnableClaim();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getAirdropStartTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDurationUntilDecay();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getDurationOfDecay();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getClaimDenom();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional bool enable_claim = 1;
 * @return {boolean}
 */
proto.evmos.claim.v1.Params.prototype.getEnableClaim = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.evmos.claim.v1.Params} returns this
 */
proto.evmos.claim.v1.Params.prototype.setEnableClaim = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp airdrop_start_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.evmos.claim.v1.Params.prototype.getAirdropStartTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.evmos.claim.v1.Params} returns this
*/
proto.evmos.claim.v1.Params.prototype.setAirdropStartTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.evmos.claim.v1.Params} returns this
 */
proto.evmos.claim.v1.Params.prototype.clearAirdropStartTime = function() {
  return this.setAirdropStartTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.evmos.claim.v1.Params.prototype.hasAirdropStartTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Duration duration_until_decay = 3;
 * @return {?proto.google.protobuf.Duration}
 */
proto.evmos.claim.v1.Params.prototype.getDurationUntilDecay = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 3));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.evmos.claim.v1.Params} returns this
*/
proto.evmos.claim.v1.Params.prototype.setDurationUntilDecay = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.evmos.claim.v1.Params} returns this
 */
proto.evmos.claim.v1.Params.prototype.clearDurationUntilDecay = function() {
  return this.setDurationUntilDecay(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.evmos.claim.v1.Params.prototype.hasDurationUntilDecay = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Duration duration_of_decay = 4;
 * @return {?proto.google.protobuf.Duration}
 */
proto.evmos.claim.v1.Params.prototype.getDurationOfDecay = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 4));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.evmos.claim.v1.Params} returns this
*/
proto.evmos.claim.v1.Params.prototype.setDurationOfDecay = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.evmos.claim.v1.Params} returns this
 */
proto.evmos.claim.v1.Params.prototype.clearDurationOfDecay = function() {
  return this.setDurationOfDecay(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.evmos.claim.v1.Params.prototype.hasDurationOfDecay = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string claim_denom = 5;
 * @return {string}
 */
proto.evmos.claim.v1.Params.prototype.getClaimDenom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.evmos.claim.v1.Params} returns this
 */
proto.evmos.claim.v1.Params.prototype.setClaimDenom = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


goog.object.extend(exports, proto.evmos.claim.v1);
