// source: evmos/erc20/v1/genesis.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var evmos_erc20_v1_erc20_pb = require('../../../evmos/erc20/v1/erc20_pb.js');
goog.object.extend(proto, evmos_erc20_v1_erc20_pb);
var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
goog.exportSymbol('proto.evmos.erc20.v1.GenesisState', null, global);
goog.exportSymbol('proto.evmos.erc20.v1.Params', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evmos.erc20.v1.GenesisState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.evmos.erc20.v1.GenesisState.repeatedFields_, null);
};
goog.inherits(proto.evmos.erc20.v1.GenesisState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evmos.erc20.v1.GenesisState.displayName = 'proto.evmos.erc20.v1.GenesisState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evmos.erc20.v1.Params = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.evmos.erc20.v1.Params, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evmos.erc20.v1.Params.displayName = 'proto.evmos.erc20.v1.Params';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.evmos.erc20.v1.GenesisState.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evmos.erc20.v1.GenesisState.prototype.toObject = function(opt_includeInstance) {
  return proto.evmos.erc20.v1.GenesisState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evmos.erc20.v1.GenesisState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.erc20.v1.GenesisState.toObject = function(includeInstance, msg) {
  var f, obj = {
    params: (f = msg.getParams()) && proto.evmos.erc20.v1.Params.toObject(includeInstance, f),
    tokenPairsList: jspb.Message.toObjectList(msg.getTokenPairsList(),
    evmos_erc20_v1_erc20_pb.TokenPair.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evmos.erc20.v1.GenesisState}
 */
proto.evmos.erc20.v1.GenesisState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evmos.erc20.v1.GenesisState;
  return proto.evmos.erc20.v1.GenesisState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evmos.erc20.v1.GenesisState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evmos.erc20.v1.GenesisState}
 */
proto.evmos.erc20.v1.GenesisState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.evmos.erc20.v1.Params;
      reader.readMessage(value,proto.evmos.erc20.v1.Params.deserializeBinaryFromReader);
      msg.setParams(value);
      break;
    case 2:
      var value = new evmos_erc20_v1_erc20_pb.TokenPair;
      reader.readMessage(value,evmos_erc20_v1_erc20_pb.TokenPair.deserializeBinaryFromReader);
      msg.addTokenPairs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evmos.erc20.v1.GenesisState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evmos.erc20.v1.GenesisState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evmos.erc20.v1.GenesisState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.erc20.v1.GenesisState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParams();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.evmos.erc20.v1.Params.serializeBinaryToWriter
    );
  }
  f = message.getTokenPairsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      evmos_erc20_v1_erc20_pb.TokenPair.serializeBinaryToWriter
    );
  }
};


/**
 * optional Params params = 1;
 * @return {?proto.evmos.erc20.v1.Params}
 */
proto.evmos.erc20.v1.GenesisState.prototype.getParams = function() {
  return /** @type{?proto.evmos.erc20.v1.Params} */ (
    jspb.Message.getWrapperField(this, proto.evmos.erc20.v1.Params, 1));
};


/**
 * @param {?proto.evmos.erc20.v1.Params|undefined} value
 * @return {!proto.evmos.erc20.v1.GenesisState} returns this
*/
proto.evmos.erc20.v1.GenesisState.prototype.setParams = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.evmos.erc20.v1.GenesisState} returns this
 */
proto.evmos.erc20.v1.GenesisState.prototype.clearParams = function() {
  return this.setParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.evmos.erc20.v1.GenesisState.prototype.hasParams = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated TokenPair token_pairs = 2;
 * @return {!Array<!proto.evmos.erc20.v1.TokenPair>}
 */
proto.evmos.erc20.v1.GenesisState.prototype.getTokenPairsList = function() {
  return /** @type{!Array<!proto.evmos.erc20.v1.TokenPair>} */ (
    jspb.Message.getRepeatedWrapperField(this, evmos_erc20_v1_erc20_pb.TokenPair, 2));
};


/**
 * @param {!Array<!proto.evmos.erc20.v1.TokenPair>} value
 * @return {!proto.evmos.erc20.v1.GenesisState} returns this
*/
proto.evmos.erc20.v1.GenesisState.prototype.setTokenPairsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.evmos.erc20.v1.TokenPair=} opt_value
 * @param {number=} opt_index
 * @return {!proto.evmos.erc20.v1.TokenPair}
 */
proto.evmos.erc20.v1.GenesisState.prototype.addTokenPairs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.evmos.erc20.v1.TokenPair, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.evmos.erc20.v1.GenesisState} returns this
 */
proto.evmos.erc20.v1.GenesisState.prototype.clearTokenPairsList = function() {
  return this.setTokenPairsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evmos.erc20.v1.Params.prototype.toObject = function(opt_includeInstance) {
  return proto.evmos.erc20.v1.Params.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evmos.erc20.v1.Params} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.erc20.v1.Params.toObject = function(includeInstance, msg) {
  var f, obj = {
    enableErc20: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    tokenPairVotingPeriod: (f = msg.getTokenPairVotingPeriod()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    enableEvmHook: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evmos.erc20.v1.Params}
 */
proto.evmos.erc20.v1.Params.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evmos.erc20.v1.Params;
  return proto.evmos.erc20.v1.Params.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evmos.erc20.v1.Params} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evmos.erc20.v1.Params}
 */
proto.evmos.erc20.v1.Params.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableErc20(value);
      break;
    case 2:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setTokenPairVotingPeriod(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableEvmHook(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evmos.erc20.v1.Params.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evmos.erc20.v1.Params.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evmos.erc20.v1.Params} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evmos.erc20.v1.Params.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnableErc20();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getTokenPairVotingPeriod();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getEnableEvmHook();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional bool enable_erc20 = 1;
 * @return {boolean}
 */
proto.evmos.erc20.v1.Params.prototype.getEnableErc20 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.evmos.erc20.v1.Params} returns this
 */
proto.evmos.erc20.v1.Params.prototype.setEnableErc20 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional google.protobuf.Duration token_pair_voting_period = 2;
 * @return {?proto.google.protobuf.Duration}
 */
proto.evmos.erc20.v1.Params.prototype.getTokenPairVotingPeriod = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 2));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.evmos.erc20.v1.Params} returns this
*/
proto.evmos.erc20.v1.Params.prototype.setTokenPairVotingPeriod = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.evmos.erc20.v1.Params} returns this
 */
proto.evmos.erc20.v1.Params.prototype.clearTokenPairVotingPeriod = function() {
  return this.setTokenPairVotingPeriod(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.evmos.erc20.v1.Params.prototype.hasTokenPairVotingPeriod = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool enable_evm_hook = 3;
 * @return {boolean}
 */
proto.evmos.erc20.v1.Params.prototype.getEnableEvmHook = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.evmos.erc20.v1.Params} returns this
 */
proto.evmos.erc20.v1.Params.prototype.setEnableEvmHook = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


goog.object.extend(exports, proto.evmos.erc20.v1);
